services:
    postgres:
        image: postgres:14
        container_name: postgres_container
        environment:
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
            POSTGRES_DB: mydatabase
        volumes:
        - postgres_data:/var/lib/postgresql/data
        ports:
        - "5432:5432"

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
        container_name: elasticsearch_container
        environment:
        - discovery.type=single-node
        - ES_JAVA_OPTS=-Xms512m -Xmx512m
        ulimits:
            memlock:
             soft: -1
             hard: -1
        volumes:
        - es_data:/usr/share/elasticsearch/data
        ports:
        - "9200:9200"
        - "9300:9300"

volumes:
    postgres_data:
    es_data:
